-- REMOVE ALL TABLES START
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Fines';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Loans';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Books';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Members';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Staff';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Author';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
-- REMOVE ALL TABLES END

-- CREATE ALL TABLES START
CREATE TABLE Author (
    AuthorID        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    AuthorName      VARCHAR2(100),
    AuthorBio       VARCHAR2(4000)
);

CREATE TABLE Members (
    MemberID       NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    MemberName     VARCHAR2(100) NOT NULL,
    MemberAddress  VARCHAR2(200),
    MemberPhone    VARCHAR2(15),
    MemberEmail    VARCHAR2(100),
    MemberPassword VARCHAR2(20) DEFAULT 'password'
);

CREATE TABLE Staff (
    StaffID       NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    StaffName     VARCHAR2(100),
    StaffRole     VARCHAR2(20),
    StaffPhone    VARCHAR2(15),
    StaffEmail    VARCHAR2(100),
    HireDate DATE,
    StaffPassword VARCHAR2(20) DEFAULT 'password'
);

CREATE TABLE Books (
    BookID          NUMBER PRIMARY KEY,
    Title           VARCHAR2(100) NOT NULL,
    AuthorID        REFERENCES Author(AuthorID),
    Publisher       VARCHAR2(100),
    Year            NUMBER(4),
    Genre           VARCHAR2(100),
    CopiesAvailable NUMBER,
    Cover           VARCHAR2(100)
);

CREATE TABLE Loans (
    LoanID     NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    BookID     REFERENCES Books(BookID),
    MemberID   REFERENCES Members(MemberID),
    StaffID    REFERENCES Staff(StaffID),
    IssueDate  DATE DEFAULT SYSDATE,
    DueDate    DATE,
    ReturnDate DATE
);

CREATE TABLE Fines (
    FineID      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    LoanID      REFERENCES Loans(LoanID),
    MemberID    REFERENCES Members(MemberID),
    StaffID    REFERENCES Staff(StaffID),
    AmountDue   NUMBER(8,2),
    AmountPaid  NUMBER(8,2),
    PaymentDate DATE
);
-- CREATE ALL TABLES END




-- CREATE ALL PROCEDURES START

-- Procedure that adds the author and book to the database
create or replace PROCEDURE AddBook (
    p_BookID NUMBER,
    p_Title VARCHAR2,
    p_Author VARCHAR2,
    p_Publisher VARCHAR2,
    p_Year NUMBER,
    p_Genre VARCHAR2,
    p_Copies NUMBER,
    p_cover VARCHAR2
)
AS
    v_AuthorID Author.AuthorID%TYPE;
    v_AuthorCheck varchar(100);
BEGIN
    BEGIN
        -- Looks to see if the author is already in the table        
        SELECT AuthorID
        INTO v_AuthorID
        FROM Author
        WHERE AuthorName = p_Author;
    EXCEPTION
        -- If there is no author, then it will add one
        WHEN NO_DATA_FOUND THEN
            INSERT INTO Author(AuthorName, AuthorBio)
            VALUES (p_Author, null);
    END;

    -- Gets the authorid from author name
    SELECT AuthorID
    INTO v_AuthorID
    FROM Author
    WHERE AuthorName = p_Author;
    
    -- Adds book to table
    INSERT INTO Books(BookID, Title, AuthorID, Publisher, Year, Genre, CopiesAvailable, cover)
    VALUES (p_BookID, p_Title, v_AuthorID, p_Publisher, p_Year, p_Genre, p_Copies, p_cover);
END;
/


-- Procedure that adds a member to the database
create or replace PROCEDURE AddMember (
    p_MemberName VARCHAR2,
    p_MemberAddress VARCHAR2,
    p_MemberPhone VARCHAR2,
    p_MemberEmail VARCHAR2,
    p_MemberPassword VARCHAR2 DEFAULT NULL
)
AS
BEGIN
    INSERT INTO Members(MemberName, MemberAddress, MemberPhone, MemberEmail, MemberPassword)
    VALUES (p_MemberName, p_MemberAddress, p_MemberPhone, p_MemberEmail, NVL(p_MemberPassword, 'password'));
END;
/


-- Procedure that adds a member to the database
create or replace PROCEDURE AddStaff (
    p_StaffName VARCHAR2,
    p_StaffRole VARCHAR2,
    p_StaffPhone VARCHAR2,
    p_StaffEmail VARCHAR2,
    p_HireDate DATE,
    p_StaffPassword VARCHAR2 DEFAULT NULL
)
AS
BEGIN
    INSERT INTO Staff(StaffName, StaffRole, StaffPhone, StaffEmail, HireDate, StaffPassword)
    VALUES (p_StaffName, p_StaffRole, p_StaffPhone, p_StaffEmail, p_HireDate, NVL(p_StaffPassword, 'password'));
END;
/

-- Procedure that checks out a book for a member
create or replace PROCEDURE CheckOutBook (
    p_BOOKID NUMBER,
    p_MEMBERID NUMBER,
    p_STAFFID NUMBER
)
AS
BEGIN
    INSERT INTO Loans(BOOKID, MEMBERID, STAFFID, ISSUEDATE)
    VALUES (p_BOOKID, p_MEMBERID, p_STAFFID, SYSDATE);
END;
/

-- CREATE ALL PROCEDURES END




-- CREATE ALL TRIGGERS START
CREATE OR REPLACE TRIGGER trg_SetDueDate
BEFORE INSERT ON Loans
FOR EACH ROW
BEGIN
    :NEW.DueDate := :NEW.IssueDate + 14;
END;
/

CREATE OR REPLACE TRIGGER trg_UpdateCopiesAvailable
AFTER INSERT OR UPDATE OF ReturnDate ON Loans
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE Books
        SET CopiesAvailable = CopiesAvailable - 1
        WHERE BookID = :NEW.BookID;
        
    ELSIF UPDATING THEN
        UPDATE Books
        SET CopiesAvailable = CopiesAvailable + 1
        WHERE BookID = :NEW.BookID;
    END IF;
END;
/

-- CREATE ALL TRIGGERS END




---- Adds test values to the books, author, and members tables
BEGIN
    -- Adds 3 test values to the book and author table
    AddBook(9781526641168, 'A Court of Thorns and Roses', 'Sarah J. Maas', 'Bloomsbury', 2015, 'Fantasy', 4, 'https://covers.openlibrary.org/b/id/13774033-L.jpg');
    AddBook (140328726, 'Fantastic Mr. Fox', 'Roald Dahl', 'Puffin', 1988, 'Animals', 3, 'https://covers.openlibrary.org/b/id/15152634-L.jpg');
    AddBook (9780593135204, 'Project Hail Mary', 'Andy Weir', 'Ballantine Books', 2021, 'hard science-fiction', 2, 'https://covers.openlibrary.org/b/id/12455001-L.jpg');
    
    -- Adds 3 test values to the members table
    AddMember('Justin Snyder', '333 SQL Lane', '5555555555', 'jsnyder@test.com');
    AddMember('Darth Vader', '444 Death Star', '3333333333', 'dvader@test.com');
    AddMember('Sylvanas Windrunner', '222 Winderunner Spire', '1234567899', 'swindrunner@test.com');
    
    -- Adds 3 test values to the staff table
    AddStaff('Debbie Grayson', 'Admin', '9876543211', 'dgrayson@test.com', SYSDATE);
    AddStaff('Samantha Eve Wilkins', 'Librarian', '9999999999', 'swilkins@test.com', SYSDATE);
    AddStaff('Mark Grayson', 'Security Guard', '8888888888', 'mgrayson@test.com', SYSDATE);
END;
/
commit;

-- Tests for checking out books to members
--BEGIN
--    --Debbie checks out 'Project Hail Mary' to Justin
--    CheckOutBook(9780593135204, 1, 1);
--    -- Samantha checks out 'A Court of Thorns and Roses' to Sylvanas 
--    CheckOutBook(9781526641168, 3, 2);
--END;
